---
- name: create timezone placeholder if it does not exists
  copy: dest=/etc/timezone
        content='#{CFG_TZ}'
        owner=root
        group=root
        mode=0644
        force=no
  become: yes
  become_user: root
  notify:
    - update timezone

- name: spanish keyboard
  lineinfile: dest=/etc/rc.local
              insertbefore='^exit'
              state=present
              line='loadkeys es'
  become: yes
  become_user: root

- name: ensure recent package list
  apt: update_cache=yes
  become: yes
  become_user: root

- name: install essential Python packages
  apt: pkg='{{ item }}' state=present
  with_items:
    - python-pip
    - python-virtualenv
    - python-software-properties
    - python-dev
    - debconf-utils
    - libzmq3-dev
    - zip
    - unzip
    - curl
    - git
    - vim
    - thrift-compiler
  sudo: yes

- name: install Python client libraries for Thrift, HBase and Jupyter
  pip: name='{{ item }}' state=present
  with_items:
    - thrift
    - happybase
    - jupyter
    - pymongo
    - ipython-sql
    - pymysql
  become: yes
  become_user: root

# - name: add Java PPA
#   apt_repository: repo=ppa:webupd8team/java state=present
#   sudo: yes

# - name: check if Java license is accepted
#   shell: '/usr/bin/debconf-get-selections | grep oracle-java7-installer'
#   sudo: yes
#   register: java_license_check
#   changed_when: java_license_check.rc != 0
#   failed_when: java_license_check.rc > 1

# - name: automatically accept Java license
#   shell: 'echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections'
#   sudo: yes
#   when: java_license_check.rc != 0


- name: install Java 8 (OpenJDK)
  apt: pkg='{{ item }}' state=present force=yes
  with_items:
    - openjdk-8-jdk
    - jython
  become: yes
  become_user: root

- name: Set JAVA_HOME environment
  lineinfile: dest=/etc/profile.d/java-env.sh
              line='export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre'
              state=present
              create=yes
  become: yes
  become_user: root

- name: fix /etc/hosts
  lineinfile: dest=/etc/hosts
              regexp='^127\.0\..*$'
              line='127.0.0.1 localhost'
              backrefs=no
              state=present
  become: yes
  become_user: root

- name: fix /etc/hosts (2)
  lineinfile: dest=/etc/hosts
              line='{{ host_ip }} {{ host_name }}'
              state=present
  become: yes
  become_user: root

- name: create base data directory
  file: path=/data state=directory owner=vagrant group=vagrant mode=0755
  become: yes
  become_user: root

- name: create SSH config
  template: src=ssh-config.j2 dest=/home/vagrant/.ssh/config

- name: create SSH key pair for Hadoop
  command: ssh-keygen -t rsa -N "" -C "for Hadoop" -f '{{ ssh_key }}'
           creates='{{ ssh_key }}.pub'

- name: add generated key to authorized_keys
  shell: 'if grep -q Hadoop /home/vagrant/.ssh/authorized_keys; then echo "public key already added"; else sed -i -e"1a`cat {{ ssh_key }}.pub`" {{ home_dir}}/.ssh/authorized_keys; fi'
  register: ssh_result
  changed_when: ssh_result.stdout.find('public key already added') == -1
