---
- name: Download and extract Hadoop2
  unarchive: src=http://ftp.rediris.es/mirror/Apache/hadoop/core/{{ hadoop_release }}/{{ hadoop_archive }}
             dest='/home/vagrant'
             creates='{{ hadoop_home_dir }}'
             copy=no

- name: symlink Hadoop home directory to just hadoop/
  file: path=/home/vagrant/hadoop src='{{ hadoop_home_dir }}' state=link

- name: add HADOOP_PREFIX to environment variables
  lineinfile: dest=/etc/environment
              regexp=^HADOOP_PREFIX=
              line=HADOOP_PREFIX={{ hadoop_home_dir }}
  sudo: yes

- name: add HADOOP_HOME to environment variables
  lineinfile: dest=/etc/profile.d/hadoop-env.sh
              line='export HADOOP_HOME=~/hadoop'
              state=present
              create=yes
  sudo: yes

- name: set JAVA_HOME environment variable for Hadoop
  lineinfile: dest='{{ hadoop_home_dir }}/etc/hadoop/hadoop-env.sh'
              regexp='^#?\s*export JAVA_HOME='
              line='export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre'
              state=present

- name: write Hadoop core config file
  template: src=hadoop-core-site.xml.j2
            dest='{{ hadoop_home_dir }}/etc/hadoop/core-site.xml'

- name: write Hadoop HDFS config file
  template: src=hadoop-hdfs-site.xml.j2
            dest='{{ hadoop_home_dir }}/etc/hadoop/hdfs-site.xml'

- name: format the Hadoop filesystem
  command: bin/hdfs namenode -format
           chdir={{ hadoop_home_dir }}
           creates={{ hadoop_tmp_dir }}
